### ISSUE TITLE
코드 인젝션(Injection) 이슈

### ISSUE THREAD

**Issue by solo5star** [nnnlog/SmartUI#1]
![](https://i.imgur.com/tQZ8aBA.jpg)

https://github.com/nnnlog/SmartUI/blob/master/src/nlog/SmartUI/FormHandlers/forms/functions/CalculatorFunction.php#L55

`eval` 을 악용하여 스크린샷과 같이 코드 Injection이 가능합니다.
오피 탈취는 물론이며 중대한 문제가 발생할 수도 있습니다.

**Comment by nnnlog** [comment]
1-9, sqrt, -, *, +, / 연산자 제외하고 다 ``` ```  으로 바꿔야겠네요

**Comment by nnnlog** [comment]
6551a956fb85cbf3d1bff88bb87855f8fde69292 로 임시적으로 차단해봅니다.
UpdateManager 에서 update.json의 version이 자신의 버전보다 클 때 메세지 등의 정보를 받아오는데 현재 플러그인 버전은 update.json 에 기록되지 않아 `존재하지 않는 배열의 키 값` 이므로 플러그인 강제 종료가 가능할 것 같습니다.

**Comment by solo5star** [comment]
이른바 킬 스위치 라는거네요

**Comment by nnnlog** [comment]
#2

**Comment by nnnlog** [comment]
closed via #5
