### ISSUE TITLE
ERROR -Altay 3.0.7

### ISSUE THREAD

**Issue by ghost** [nnnlog/SmartUI#4]
18:56:43 NOTICE > [SmartUI] 새로운 버전이 나왔습니다. 현재 버전 : 2.2.5, 99999
18:56:44 NOTICE > [SmartUI] 새버전으로 업데이트 되었습니다. 재부팅 시 적용됩니다.
18:56:44 CRITICAL > [SmartUI] 업데이트 적용을 위해 서버가 꺼집니다...
18:56:44 NOTICE > [SmartUI] 새버전으로 업데이트가 필요합니다. 플러그인이 비활성화됩니다.
18:56:44 CRITICAL > Error: "Call to undefined method pocketmine\plugin\PharPluginLoader::disablePlugin()" (EXCEPTION) in "SmartUI.phar/src/nlog/SmartUI/util/UpdateManager" at line 71
18:56:44 DEBUG > #0 SmartUI.phar/src/nlog/SmartUI/SmartUI(44): nlog\SmartUI\util\UpdateManager->checkUpdate()
18:56:44 DEBUG > #1 src/pocketmine/plugin/PluginBase(111): nlog\SmartUI\SmartUI->onEnable()
18:56:44 DEBUG > #2 src/pocketmine/plugin/PluginManager(615): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
18:56:44 DEBUG > #3 src/pocketmine/Server(2037): pocketmine\plugin\PluginManager->enablePlugin(nlog\SmartUI\SmartUI object)
18:56:44 DEBUG > #4 src/pocketmine/Server(2023): pocketmine\Server->enablePlugin(nlog\SmartUI\SmartUI object)
18:56:44 DEBUG > #5 src/pocketmine/Server(1792): pocketmine\Server->enablePlugins(integer 1)
18:56:44 DEBUG > #6 src/pocketmine/PocketMine(241): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\ghkst\Desktop\Altay-master\, string C:\Users\ghkst\Desktop\Altay-master\plugins\)
18:56:44 DEBUG > #7 C:/Users/ghkst/Desktop/Altay-master/Altay.phar(1): require_once(string phar://C:/Users/ghkst/Desktop/Altay-master/Altay.phar/src/pocketmine/PocketMine.php)

**Comment by nnnlog** [comment]
Altay는 지원 계획에 없습니다.
